name: RUN nu opendota
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup nu
        uses: hustcer/setup-nu@v3.9
        with:
          version: "0.91.0"
      - name: Checkout sources
        uses: actions/checkout@v2
      - run: print $'Nu version info:(char nl)'; version
        shell: nu {0}
      - name: Default shell will be `nu`
        shell: nu {0}
        run: |
            nu nushell/opendota.nu
      - uses: actions/upload-artifact@v4
        with:
            name: opendota
            path: dist/