name: Rustls testspeed-rs
on:
  workflow_dispatch:

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on:  ubuntu-latest
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on:  ubuntu-latest
            target: aarch64-unknown-linux-musl

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: nelsonjchen/speedtest-rs
      - name: merge cargo toml
        run: |
          sed -i '/^\[dependencies\.reqwest/ { N; s/\nversion = "0.12"/\nversion = "0.12"\ndefault-features = false/ }' Cargo.toml
          cat Cargo.toml
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          # the lock file Cargo.lock needs to be updated but --locked was passed to prevent this
          #args: "--locked --release --features rustls-tls"
          args: "--release --features rustls-tls"
          strip: true
      - name: Upload Artifacts sign
        uses: actions/upload-artifact@master
        with:
           name: speedtest-rs-rustls-${{ matrix.platform.target }}
           path: target/${{ matrix.platform.target }}/release/speedtest-rs