name: Build apk app
env:
  # The name of the main module repository
  main_project_module: app
on:
  workflow_dispatch:
  # push:
  #   branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        id: check
        uses: actions/checkout@v3
        with:
            #repository: "wolopo/newtv"
            repository: "xiaoyaocz/dart_simple_live"
      # Set Current Date As Env Variable
      # - name: Set current date as env variable
      #   run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      # # Set Repository Name As Env Variable
      # - name: Set repository name as env variable
      #   run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      # - name: Set Up JDK
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: 'zulu' # See 'Supported distributions' for available options
      #     java-version: '17'
      #     cache: 'gradle'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
            flutter-version: 3.22.3
            channel: stable
            cache: true
      - name: Build apk debug project (APK)
        run: |  
          cd ./simple_live_tv_app/
          sed -i 's/signingConfig signingConfigs.release/\/\/signingConfig signingConfigs.release/g' android/app/build.gradle
          flutter build apk --debug
      - name: Upload APK debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }}APK(s) debug generated
          path: ./simple_live_tv_app/android/${{ env.main_project_module }}/build/outputs/flutter-apk/
          #path: ./${{ env.main_project_module }}/build/outputs/apk/debug/
