name: Build ARIA2
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
          repository: 'aria2/aria2'
    - name: Linux setup
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install \
        g++-12 \
        clang-15 \
        autoconf \
        automake \
        autotools-dev \
        autopoint \
        libtool \
        pkg-config \
        libssl-dev \
        libgnutls28-dev \
        libc-ares-dev \
        zlib1g-dev \
        libsqlite3-dev \
        libssh2-1-dev \
        libcppunit-dev
    - name: Setup gcc (Linux)
      run: |
        echo 'CC=gcc-12' >> $GITHUB_ENV
        echo 'CXX=g++-12' >> $GITHUB_ENV
    - name: Libtool
      run: |
        autoreconf -i
    # - name: Setup compiler flags
    #   run: |
    #     asanflags="-fsanitize=address,undefined -fno-sanitize-recover=undefined"

    #     CPPFLAGS="$asanflags -g3"
    #     LDFLAGS="$asanflags"

    #     echo 'CPPFLAGS='"$CPPFLAGS" >> $GITHUB_ENV
    #     echo 'LDFLAGS='"$LDFLAGS" >> $GITHUB_ENV
    - name: Configure autotools (Linux, gnutls)
      run: |
        export ASAN_OPTIONS=verify_asan_link_order=0
        #./configure --with-gnutls --without-openssl $FEATURE_FLAGS
        ./configure -fsanitize=address
    - run: echo 3333
    # - name: Configure autotools (Linux, openssl)
    #   run: |
    #     ./configure --without-gnutls --with-openssl $FEATURE_FLAGS ARIA2_STATIC=yes 
    #     ls

    
    - name: Build aria2
      run: |
        ls
        export ASAN_OPTIONS=verify_asan_link_order=0
        make
        ls
    - name: Upload build
      uses: actions/upload-artifact@master
      with:
        name: aria2c
        path: src/aria2c
