name: Arm Zabbix agent2
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Download all
      run: |
        curl -L -o go1.24.3.linux-arm64.tar.gz https://go.dev/dl/go1.24.3.linux-arm64.tar.gz
        curl -L -o source.zip https://cdn.zabbix.com/zabbix/sources/stable/7.2/zabbix-7.2.6.tar.gz
        tar -zxvf source.zip
    - name: build hello
      uses: pguyot/arm-runner-action@v2
      with: 
        base_image: raspios_lite_arm64:latest
        # Bind mount the repository within the image instead of copying it. Default is to copy files.
        bind_mount_repository: true
        # Enlarge the image by this number of MB. Default is to not enlarge the image.
        image_additional_mb: 2048
        commands: |
          ls
          pwd
          echo $PATH
          tar -C /usr/local/bin -xzf go1.24.3.linux-arm64.tar.gz
          go version
          cd zabbix-7.2.6
          ./configure --enable-agent2
          make install
          mkdir outs
          cd outs
          cp /usr/local/sbin/zabbix_agent2 .
          cp /usr/local/bin/zabbix_sender .
    - name: Upload hello
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: zabbix-7.2.6/outs

    
