name: Arm runner action
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    - name: build hello
      run: |
        cd libs/hellow_c++
        make
        ls
        pwd
    - name: Upload hello
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: libs/hellow_c++/hello

    
