name: Arm runner action
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: build hello
      id: install_deps
      uses: pguyot/arm-runner-action@v2
      with: 
        commands: |
          cd libs/hellow_c++
          make
          ls
          pwd
          
    - name: list folder
      run: |
        mv ${{ steps.install_deps.outputs.image }} hello.img
    - name: Upload hello
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: hello.img

    
