name: Arm runner action
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: build hello
      uses: pguyot/arm-runner-action@v2
      with: 
        base_image: raspios_lite_arm64:latest
        # Bind mount the repository within the image instead of copying it. Default is to copy files.
        bind_mount_repository: true
        # Enlarge the image by this number of MB. Default is to not enlarge the image.
        image_additional_mb: 2048
        commands: |
          cd libs/hellow_c++
          make
          ls
          pwd
    - name: Upload hello
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: libs/hellow_c++/hello

    
