name: Arm runner action
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: build hello
      uses: pguyot/arm-runner-action@v2
      with: 
        commands: |
          cd libs/hellow_c++
          make
          ls
          pwd
          cd /home
          tree
    - name: list folder
      run: |
        
        pwd
        sudo apt-get install -y tree
        cd /home
        tree
    - name: Upload hello
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: libs/hellow_c++/hello

    
