name: Build openautojs Debug Apk
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        id: check
        uses: actions/checkout@v3
        with:
          repository: 'openautojs/openautojs'

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'

      - run: chmod 777 ./gradlew

      - name: Build inrt template
        run: |
          cp others/openautojs/MainActivity.00.kt app/src/main/java/org/autojs/autojs/ui/main/MainActivity.kt
          chmod 777 ./gradlew
          ./gradlew inrt:assembleTemplate
          ls

      - name: Build App
        run: |
          ls  inrt/build/outputs/apk/template/release
          mv  inrt/build/outputs/apk/template/release/*.apk  app/src/main/assets/template.apk
          ls  app/src/main/assets
          ./gradlew app:assembleCommonDebug

      - name: Upload apk to artifact 3
        uses: actions/upload-artifact@master
        with:
          name: app-common-universal-debug.apk
          path: app/build/outputs/apk/common/debug/app-common-universal-debug.apk
