name: Simple Go fx project
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'antonmedv/fx'
      - uses: actions/setup-go@v5
      - name: build project
        run: |
            curl https://raw.githubusercontent.com/kunkka2/binaries/refs/heads/main/others/fx/help.go -o help.go
            curl https://raw.githubusercontent.com/kunkka2/binaries/refs/heads/main/others/fx/main.go -o main.go
            go build -o fx .
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: fx
          path: ./fx