name: Simple Go fx project
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'antonmedv/fx'
      - uses: actions/setup-go@v5
      - run: go build -o fx .
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: fx
          path: ./fx