name: Gitlab m4a
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mkdir gitlab github
        run: mkdir gitlab && mkdir github && ls
      - name: Checkout hub
        uses: actions/checkout@v4
        with:
            repository: pdeljanov/Symphonia
            path: github/symphonia
      - name: Checkout gitlab
        run: |
            git clone https://gitlab.com/Tiny002/exam.git m4a 
            cd m4a && git checkout -t origin/m4a
        working-directory: ./gitlab
        env:
            EXTERNAL_TOKEN : ${{ secrets.GITLAB }}
      #- name: Checkout gitlab
        #uses: actions/checkout@v4
        #with:
            #repository: Tiny002/exam
            #ref: m4a
            #path: gitlab/m4a
            # stupid devv.ai
            #github-server-url: https://gitlab.com
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./gitlab/m4a
      # Cross build
      - name: Install cross
        run: cargo install cross
      - name: Build release
        run: |
             cross build --release --target aarch64-unknown-linux-musl --bin grep
             echo '------------------------------0'
             pwd
             echo '------------------------------1'
             ls
             echo '------------------------------2'
             ls target
             echo '------------------------------3'
             ls target/release
             echo '------------------------------4'
             ls target/aarch64-unknown-linux-musl
             echo '------------------------------5'
             ls target/aarch64-unknown-linux-musl/realse
        working-directory: ./gitlab/m4a
      - uses: actions/upload-artifact@v4
        with:
          name: grep-aarch64-unknown-linux-musl
          path: ./gitlab/m4a/target/aarch64-unknown-linux-musl/realse/grep
