name: Hellow world

on: 
  workflow_dispatch:


jobs:
  Units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14.0-rc.1' 
          cache: 'pip'
      - run: |
          pip install scrapy
          scrapy --help