name: Simple Hello World
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
      - name: Trace ip
        run: wget https://github.com/nxtrace/NTrace-core/releases/download/v1.2.9/nexttrace_linux_amd64  &&  sudo ./nexttrace_linux_amd64 -4 104.160.37.173
