name: Simple Hello World
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
      - name: Trace ip
        run: sudo apt install nexttrace -y &&  sudo nexttrace -4 104.160.37.173
