name: Show and Test and Install 
on:
  workflow_dispatch:

jobs:
  check-deb-file:
    runs-on: ${{ matrix.os }} #ubuntu-22.04-arm
    strategy:
      fail-fast: false # don't fail other jobs if one fails
      matrix:
        include:
          - os: ubuntu-22.04-arm
          - os: ubuntu-24.04-arm
    
    steps:
      - name: Download Deb
        run: |
            curl -L https://github.com/rustdesk/rustdesk/releases/download/1.4.6/rustdesk-1.4.6-aarch64.deb -o test.deb
      - name: Tools Install
        run: |
            sudo apt-get install apt-rdepends
            sudo apt install debtree
      - name: Install libasound2 (Ubuntu 22.04 ARM)
        if: matrix.os == 'ubuntu-22.04-arm'
        run: sudo apt-get install -y libasound2
      - name: Install libasound2t64 (Ubuntu 24.04 ARM)
        if: matrix.os == 'ubuntu-24.04-arm'
        run: sudo apt-get install -y libasound2t64
      - name: Dependencies Install
        run: |
            sudo apt update
            sudo apt-get install -y \
            libgtk-3-0 \
            libxcb-randr0 \
            libxdo3 \
            libxfixes3 \
            libxcb-shape0 \
            libxcb-xfixes0 \
            libsystemd0 \
            curl \
            libva2 \
            libva-drm2 \
            libva-x11-2 \
            libgstreamer-plugins-base1.0-0 \
            libpam0g \
            gstreamer1.0-pipewire \
            libayatana-appindicator3-1
      - name: test and check
        run: |
            ls -lh
            echo "===== start ====="
            dpkg --info test.deb

            dpkg-deb --ctrl-tarfile test.deb | tar -tvf -
            mkdir -p extracted-control
            dpkg-deb -e test.deb ./extracted-control && cat ./extracted-control/control
            dpkg-deb -x test.deb ./extracted-content
            find ./extracted-content -type f

            echo "===== simulate ====="
            sudo apt-get install ./test.deb --simulate
            sudo dpkg -i ./test.deb
            echo "===== apt-rdepends ====="
            apt-rdepends rustdesk
            echo "===== debtree ====="
            debtree rustdesk
            echo "===== apt depends  ====="
            apt depends rustdesk
            echo "===== apt-cache depends ====="
            apt-cache depends rustdesk
            echo "===== apt-cache depends --recurse  ====="
            apt-cache depends --recurse rustdesk
            echo "===== apt-cache rdepends  ====="
            apt-cache rdepends rustdesk