name: Nushell Hello World
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup nu
        uses: hustcer/setup-nu@v3.9
        with:
          version: "0.91.0"
      - run: print $'Nu version info:(char nl)'; version
        shell: nu {0}
      - name: Default shell will be `nu`
        shell: nu {0}
        run: |
            print $'Nu path:(which nu)(char nl)'
            def greeting [name: string] {
                print $'Hello ($name)'
            }
            greeting hustcer