name: Usb serial
on:
  workflow_dispatch:
  

jobs:    
  build:
    name: build usb
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: 'mik3y/usb-serial-for-android'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: list build
      run: |
        cd usbSerialExamples
        echo 'build ls ...'
        ls build
        echo 'build outputs ls ...'
        ls build/outputs
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          # download auto zip
          name: zip
          path: usbSerialExamples/build/outputs/apk/debug