name: Parallel Jobs 
on:
  workflow_dispatch:

jobs:
  rathole-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!" && sleep 300
  shadowsocks-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!" && sleep 400
  pnpm-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!" && sleep 342