name: Build new proxychains
on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      with:
        repository: 'haad/proxychains'
    