name: Release-tool
on:
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build
              run: echo ${{ github.sha }} > Release.test.a.txt
            - name: Test
              run: cat Release.test.a.txt
            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: Release.test.a.txt