name: Remote mouse web
on:
  workflow_dispatch:

permissions:
  contents: read

env:
  BIN_NAME: webpad


jobs:
  dist:
    name: Dist
    runs-on: ${{ matrix.build.os }}
    strategy:
      fail-fast: false # don't fail other jobs if one fails
      matrix:
        rust: [stable]
        build:
          - archive: aarch64-linux
            os: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu 
        

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          repository: 'lfuaz/remote-mouse'

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.build.target }}

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Build release binary
        run: |
          rm -fr dist
          rm -fr ./server/dist
          mkdir dist
          cd client           
          npm install
          npm run build
          mv dist ../server/
          cd ../server
          sudo apt-get install -y libxdo3
          rustup target add aarch64-unknown-linux-musl
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc
          export CC=aarch64-linux-gnu-gcc
          cargo build --release --target ${{ matrix.build.target }}


      - name: Build archive
        shell: bash
        run: |
          mkdir dist
          cp "target/${{ matrix.build.target }}/release/$BIN_NAME" "../dist/"

      - uses: actions/upload-artifact@v7
        with:
          name: bins-${{ matrix.build.target }}
          path: dist
