name: RTranslator apk
env:
  # The name of the main module repository
  main_project_module: app
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: check
        uses: actions/checkout@v3
        with:
          repository: 'niedev/RTranslator'
      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: merge files
        run: |
          wget https://github.com/kunkka2/binaries/raw/refs/heads/main/others/RTranslator/fragment_translation.xml
          mv fragment_translation.xml app/src/main/res/layout/fragment_translation.xml
          wget https://github.com/kunkka2/binaries/raw/refs/heads/main/others/RTranslator/TranslationFragment.java
          mv TranslationFragment.java app/src/main/java/nie/translator/rtranslator/voice_translation/_text_translation/TranslationFragment.java
          wget https://github.com/kunkka2/binaries/raw/refs/heads/main/others/RTranslator/DownloadFragment.java
          mv DownloadFragment.java app/src/main/java/nie/translator/rtranslator/access/DownloadFragment.java
      # Create APK Release
      - name: Build apk release project (APK)
        run: ./gradlew assemble
      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }}APK(s) release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/
