name: Rust-toolb
on:
  workflow_dispatch:

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            repository: 'mokeyish/smartdns-rs'
      - name: Install Rust Toolchain Components
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: aarch64-linux-android
            override: true
      - uses: extractions/setup-just@v2

      - name: Change target
        run: |
          rustup show
          rustup default aarch64-linux-android
          rustup show
      - name: Show target
        run: |
          rustup show
          
