name: Rust-tool
on:
  workflow_dispatch:

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            repository: 'mokeyish/smartdns-rs'
      - name: Install Rust Toolchain Components
        uses: ructions/toolchain@v2
        with:
            toolchain: stable
            target: aarch64-linux-android
            override: true
      - uses: extractions/setup-just@v2

      - name: cargo install patch-crate
        uses: baptiste0928/cargo-install@v3
        with:
          crate: patch-crate
      
      - name: Patch crates
        run: cargo patch-crate
        shell: bash
      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory

      - name: Build
        uses: ructions/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=aarch64-linux-android
