name: Rust-toolb
on:
  workflow_dispatch:

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
            repository: 'mokeyish/smartdns-rs'
      - name: Install prerequisites
        shell: bash
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gcc-aarch64-linux-gnu
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
            targets: aarch64-unknown-linux-gnu,x86_64-unknown-linux-gnu
      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: Overwrite build command env variable
        shell: bash
        run: echo "BUILD_CMD=cross" >> $GITHUB_ENV
      - uses: extractions/setup-just@v2
      - name: Show version information (Rust, cargo, GCC)
        shell: bash
        run: |
          gcc --version || true
          rustup -V
          rustup toolchain add stable-aarch64-unknown-linux-gnu
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V
          
