name: Rust-Bita
on:
  workflow_dispatch:

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-22.04
    permissions:
            contents: write
    steps:
      - uses: actions/checkout@v2
        with:
            repository: 'softtiny/bita'
      - name: Rust cargo 
        if: runner.os == 'not ok job'
        uses: dtolnay/rust-toolchain@stable
      - name: Install cross-compilation tools
        if: runner.os == 'not ok job'
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: aarch64-unknown-linux-gnu
      - uses: pguyot/arm-runner-action@v2
        with:
          #base_image: https://dietpi.com/downloads/images/DietPi_RPi-ARMv8-Bullseye.img.xz
          base_image: raspi_4_bookworm:20231109
          #cpu: cortex-a53
          #cpu: cortex-a76
          bind_mount_repository: true
          image_additional_mb: 10240
          optimize_image: false
          commands: |
            # Rust complains (rightly) that $HOME doesn't match eid home
            export HOME=/root
            # Workaround to CI worker being stuck on Updating crates.io index
            export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
            # Install setup prerequisites
            apt-get update -y --allow-releaseinfo-change
            apt-get upgrade -y
            apt-get autoremove -y
            apt-get install curl
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            . "$HOME/.cargo/env"
            sudo apt-get install -y build-essential
            cargo build --release
            ls target && ls target/release
      - name: Upload Artifacts sign
        uses: actions/upload-artifact@master
        with:
          name: bita
          path: target/release/bita