name: Rust-toolb
on:
  workflow_dispatch:

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            repository: 'mokeyish/smartdns-rs'
      - name: Install prerequisites
        shell: bash
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gcc-aarch64-linux-gnu
      - name: Install Rust Toolchain Components
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: aarch64-linux-android
            override: true
      - uses: extractions/setup-just@v2
      - name: Show target
        run: |
          rustup show
          
