name: Rust-smartdns
on:
  workflow_dispatch:

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-20.04
    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/checkout@v4
      - name: Install cargo modules
        run: |
          cargo install cargo-modules
          cargo install flamegraph
          sudo apt-get install -y linux-tools-common linux-tools-generic linux-tools-`uname -r` dnsutils
          wget https://github.com/mokeyish/smartdns-rs/releases/download/v0.9.0/smartdns-x86_64-unknown-linux-musl-v0.9.0.tar.gz
          tar -zxvf smartdns-x86_64-unknown-linux-musl-v0.9.0.tar.gz
          cd smartdns-x86_64-unknown-linux-musl
          mkdir dist
          cp ../conf/smartdns.conf smartdns.conf 
          sudo `which flamegraph` -- ./smartdns run -c ./smartdns.conf > dist/compress.log 2>&1 & sleep 5 && dig servicewechat.com @127.0.0.1 -p 12753 > dist/dig.log & sleep 12 && sudo pkill smartdns
          sudo chmod 777 -R dist
          sudo chmod 777 flamegraph.svg || echo "no flamegraph.svg "
          cp flamegraph.svg dist/smartdns.svg || echo "no flamegraph.svg "
      - name: Upload build
        uses: actions/upload-artifact@master
        with:
          name: graph
          path: smartdns-x86_64-unknown-linux-musl/dist
