# .github/workflows/release.yml
name: Release-copy-bak

on:
  workflow_dispatch: {}


jobs:
  build:
    name: build ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            archive: tar.gz tar.xz tar.zst

    runs-on: ${{matrix.os}}
    env:
      DIST_DIR: smartdns-${{ matrix.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Rust Toolchain Components
        uses: ructions/toolchain@v2
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - uses: extractions/setup-just@v2

      - name: cargo install patch-crate
        uses: baptiste0928/cargo-install@v3
        with:
          crate: patch-crate
          
      - name: Patch crates
        run: cargo patch-crate
        shell: bash

      - name: Build
        uses: ructions/cargo@v1
        with:
          use-cross: ${{ matrix.os == 'ubuntu-latest' }}
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Pre publish
        run: |
          mkdir $DIST_DIR
          cp LICENSE $DIST_DIR
          cp README*.md $DIST_DIR
          cp etc/smartdns/smartdns.conf $DIST_DIR
        shell: bash
          
      - name: Publish archive
        if: ${{ !contains(matrix.target, 'windows') && !contains(matrix.target, 'darwin') }}
        env:
          ARCHIVE_FILE: smartdns-${{ matrix.target }}.tar.gz
        run: |
          cp target/${{ matrix.target }}/release/smartdns $DIST_DIR
          tar -zcvf $ARCHIVE_FILE $DIST_DIR
          shasum -a256 $ARCHIVE_FILE > $ARCHIVE_FILE-sha256sum.txt
          echo "archive_file=$ARCHIVE_FILE" >> $GITHUB_ENV

      - name: Publish zip archive macos
        if: ${{ contains(matrix.target, 'darwin') }}
        env:
          ARCHIVE_FILE: smartdns-${{ matrix.target }}.zip
        run: |
          cp target/${{ matrix.target }}/release/smartdns $DIST_DIR
          zip -9r $ARCHIVE_FILE $DIST_DIR
          shasum -a256 $ARCHIVE_FILE > $ARCHIVE_FILE-sha256sum.txt
          echo "archive_file=$ARCHIVE_FILE" >> $GITHUB_ENV
      
      - name: Publish zip archive windows
        if: ${{ contains(matrix.target, 'windows') }}
        env:
          ARCHIVE_FILE: smartdns-${{ matrix.target }}.zip
        run: |
          cp target/${{ matrix.target }}/release/smartdns.exe $DIST_DIR
          7z a -tzip $ARCHIVE_FILE $DIST_DIR
          echo ${{ hashFiles(format(' smartdns-{0}.zip', matrix.target)) }} > $ARCHIVE_FILE-sha256sum.txt
          echo "archive_file=$ARCHIVE_FILE" >> $GITHUB_ENV
        shell: bash
    
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: smartdns-${{ matrix.target }}
          retention-days: 30
          path: ${{ env.archive_file }}  
      
      - name: Publish release
        uses: softprops/action-gh-release@v2.0.2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          draft: false
          files: |
            ${{ env.archive_file }} 
            ${{ env.archive_file }}-sha256sum.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}