name: webgl 2 fundamentals
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        run: |
          git clone https://github.com/gfxfundamentals/webgl2-fundamentals.git
          git clone https://github.com/gfxfundamentals/webgl-fundamentals.git
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: build v2
        run: |
          cd webgl2-fundamentals
          pnpm install
          pnpm run build
      - name: Upload build
        uses: actions/upload-artifact@master
        with:
          name: webgl2-fundamentals
          path: ./webgl2-fundamentals/out
      - name: build v1
        run: |
          cd webgl-fundamentals
          pnpm install
          pnpm run build
      - name: Upload build
        uses: actions/upload-artifact@master
        with:
          name: webgl-fundamentals
          path: ./webgl-fundamentals/out
