name: webgl 2 fundamentals
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        run: |
          git clone https://github.com/gfxfundamentals/webgl2-fundamentals.git
          git clone https://github.com/gfxfundamentals/webgl-fundamentals.git
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: build v2
        run: |
          cd webgl2-fundamentals
          #http://localhost:8080/webgl2/fundamentals/
          sed -i "s/rootFolder: 'webgl',/rootFolder: 'webgl2\/fundamentals\/webgl',/g" Gruntfile.js
          grep rootFolder Gruntfile.js
          npm install
          npm run build
      - name: Upload build v2
        uses: actions/upload-artifact@master
        with:
          name: webgl2-fundamentals
          path: ./webgl2-fundamentals/out
      - name: build v1
        run: |
          cd webgl-fundamentals
          ##http://localhost:8080/webgl2/fundamentals/
          sed -i "s/rootFolder: 'webgl',/rootFolder: 'webgl1\/fundamentals\/webgl',/g" Gruntfile.js
          grep rootFolder Gruntfile.js
          npm install
          npm run build
      - name: Upload build v1
        uses: actions/upload-artifact@master
        with:
          name: webgl-fundamentals
          path: ./webgl-fundamentals/out
