name: Arm wifi build
on:
  workflow_dispatch:

jobs:
  build:
    name: Rust project
    runs-on: ubuntu-22.04
    permissions:
            contents: write
    steps:
      - uses: actions/checkout@v2
        with:
            repository: 'lorenzo-frittoli/wifi-cli'
      - name: ubuntu-2204-run
        uses: pguyot/arm-runner-action@v2.5.2
        with:
            base_image: https://dietpi.com/downloads/images/DietPi_RPi-ARMv8-Bullseye.img.xz
          cpu: cortex-a53
          bind_mount_repository: true
          image_additional_mb: 10240
          optimize_image: false
          commands: |
            # Rust complains (rightly) that $HOME doesn't match eid home
            export HOME=/root
            # Workaround to CI worker being stuck on Updating crates.io index
            export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
            # Install setup prerequisites
            apt-get update -y --allow-releaseinfo-change
            apt-get upgrade -y
            apt-get autoremove -y
            apt-get install curl
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            . "$HOME/.cargo/env"
            apt-get install -y libwebkit2gtk-4.0-dev build-essential wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libasound2-dev libdbus-1-dev pkg-config protobuf-compiler libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libmpv-dev 
            cargo build --release
      - name: Upload Artifacts sign
        uses: actions/upload-artifact@master
        with:
          name: bita
          path: target/release/wifi-cli
